---
apiVersion: v1
kind: Secret
metadata:
  name: secret-for-test
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:maugros/k8s.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDI8VgD4GO8iMtq0GG0e7fSg33p6N4bANcE8xNuc3mb0gAAAJhgmzdaYJs3
    WgAAAAtzc2gtZWQyNTUxOQAAACDI8VgD4GO8iMtq0GG0e7fSg33p6N4bANcE8xNuc3mb0g
    AAAEAypNUVeRPsg494384VNA/7B7sVpEPm+qUT/WklnJ8UGcjxWAPgY7yIy2rQYbR7t9KD
    feno3hsA1wTzE25zeZvSAAAAEWFyZ29jZEBnaXRsYWIuY29tAQIDBA==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"